This patch was developed in-house, and submitted upstream:
http://bugs.python.org/issue26414

--- Python-3.4.4/Lib/posixpath.py.orig	2015-12-20 22:00:59.000000000 -0800
+++ Python-3.4.4/Lib/posixpath.py	2016-02-19 13:05:44.295727065 -0800
@@ -31,7 +31,7 @@
 extsep = '.'
 sep = '/'
 pathsep = ':'
-defpath = ':/bin:/usr/bin'
+defpath = '/bin:/usr/bin'
 altsep = None
 devnull = '/dev/null'
 
