In-house patch to remove the reference to glance_store's tests in the
Python package's entry_points.txt file. Without this change, a warning
is printed in some of the Glance service logs. Not suitable for the
upstream.

--- glance_store-0.13.0/setup.cfg.~1~	2016-03-03 07:33:51.000000000 +0000
+++ glance_store-0.13.0/setup.cfg	2016-09-06 17:03:27.304396117 +0000
@@ -33,8 +33,6 @@ glance_store.drivers =
 	sheepdog = glance_store._drivers.sheepdog:Store
 	cinder = glance_store._drivers.cinder:Store
 	vmware = glance_store._drivers.vmware_datastore:Store
-	# TESTS ONLY
-	no_conf = glance_store.tests.fakes:UnconfigurableStore
 	# Backwards compatibility
 	glance.store.filesystem.Store = glance_store._drivers.filesystem:Store
 	glance.store.http.Store = glance_store._drivers.http:Store
